#!/usr/bin/env node
/**
 * Reads the compiled WASM file, base64-encodes it, and writes an auto-generated
 * TypeScript module that the SemanticStateEngine can import to avoid runtime
 * file-path and MIME-type issues.
 *
 * Run: node scripts/inline-wasm.mjs
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const wasmPath = resolve(root, "src/wasm-pkg/semantic_state_core_bg.wasm");
const outPath = resolve(root, "src/wasm-pkg/wasm_inline.ts");

const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString("base64");

const content = `// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit manually.
// This file is re-generated whenever the Rust crate is rebuilt with wasm-pack.
export const WASM_BASE64 =
  "${base64}";
`;

writeFileSync(outPath, content, "utf8");
console.log(
  `[inline-wasm] Wrote ${(wasmBytes.length / 1024).toFixed(1)} KB of WASM ` +
    `(${(base64.length / 1024).toFixed(1)} KB base64) → src/wasm-pkg/wasm_inline.ts`
);
